server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: API GATEWAY
  cloud:
    gateway:
      routes:
        - id: batch-service
          uri: lb://batch-service
          predicates:
            - Path=/batch/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
          filters:
            - AuthenticationFilter
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
          filters:
            - AuthenticationFilter
                        
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - AuthenticationFilter	         
            
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**             
          filters:
            - AuthenticationFilter