server:
  port: 8999
  
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: API GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
        - id: batch-service
          uri: lb://batch-service
          predicates:
            - Path=/batch/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/** 
        - id: student-service
          uri: lb://teacher-service
            - Path=/student/**
            
          
          
             
            
             
  
